name: unicorn_color
description: This package provides top unicorn Brand colors.
version: 0.0.1
homepage: https://github.com/Monzim/unicorn_color

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
